input_output.o: input_output.c input_output.h 
	gcc -Wall -g -c input_output.c

install: input_output.o input_output.h
	cp -v input_output.o ../lib/input_output.o
	cp -v input_output.h ../include/input_output.h
